### ISSUE TITLE
In power shell 5 the parameter IV is now reserved as an alias

### ISSUE THREAD

**Issue by joshuaitguy** [dlwyatt/ProtectedData#13]
Well I realize that Windows 10 and PS 5 are still going through their testing I suspect this probably won't be changing come release time.  Specifically the error is: Protect-DataWithAes : The parameter 'IV' cannot be specified because it conflicts with the parameter alias of the same name for parameter 'InformationVariable'.  This was returned when running the Protect-Data cmdlet.

**Comment by dlwyatt** [comment]
Well that's annoying.  Thanks for the heads-up!  Will fix tomorrow.
